Closes #11 Define sphere shape
INDAPlus20/isaklar-ahanifi-maltebl-lervik-project pull request #14
Opened 2021-04-20 13:25 UTC by coffecup25

2021-04-20 13:45 UTC, isakvlarsson requested changes

2021-04-20 13:45 UTC, isakvlarsson commented on pphysx3d/Cargo.toml
> +authors = ["arian"]
lmao

2021-04-20 13:45 UTC, isakvlarsson commented on pphysx3d/src/shapes/mod.rs
> +    direction: Vector3<f32>,
Bör vara Unit<Vector3<f32>> om det är en unit-vector, enligt nalgebras docs

2021-04-20 13:47 UTC, coffecup25 commented on pphysx3d/src/shapes/mod.rs
> +    direction: Vector3<f32>,
Lite kvarlämningar från maltes snabba genomgång av vad som potentiellt behövs. Kommer att bearbetas senare

2021-04-20 13:48 UTC, coffecup25 commented on pphysx3d/Cargo.toml
> +authors = ["arian"]
ahaha xD ganska trevlig email om jag får säga så själv. Förresten ni vill kanske också vara med som authors?

2021-04-21 12:11 UTC, M-Blomqvist requested changes

2021-04-21 12:11 UTC, M-Blomqvist commented on pphysx3d/src/shapes/mod.rs
> +// }
```suggestion
```
Remove unnecessary old code

2021-04-21 12:11 UTC, M-Blomqvist commented on pphysx3d/src/shapes/tests.rs
> +}
```suggestion
```
Remove unrelated old test

2021-04-21 12:15 UTC, isakvlarsson approved these changes

2021-04-21 12:16 UTC, M-Blomqvist approved these changes

2021-04-21 12:16 UTC, axellervik approved these changes

2021-04-21 12:16 UTC, merged