Feature/23 plane struct
INDAPlus20/isaklar-ahanifi-maltebl-lervik-project pull request #33
Opened 2021-05-06 17:45 UTC by isakvlarsson

Closes #23

2021-05-06 19:58 UTC, coffecup25 commented on pphysx3d/src/shapes/bounding_volume.rs
> -      pub fn mins(&self) -> Point3<f32>{
This man just wants to add more lines to his stats

2021-05-06 19:59 UTC, coffecup25 commented on pphysx3d/src/shapes/bounding_volume.rs
> +    }
This man just wants to add more lines to his stats

2021-05-06 20:00 UTC, coffecup25 approved these changes

2021-05-07 10:01 UTC, M-Blomqvist requested changes
Probably still gonna break, should've pulld main

2021-05-07 10:01 UTC, M-Blomqvist commented on pphysx3d/src/shapes/plane.rs
> +    }
```suggestion
    fn as_sphere(&self) -> Result<&Sphere,()> {
        return Err(());
    }
    
    fn as_cube(&self) -> Result<&Cube,()> {
        return Err(());
    }
```

2021-05-07 10:04 UTC, isakvlarsson commented
> Probably still gonna break, should've pulld main

What kind of changes do you want me to make? 🙂

2021-05-07 10:16 UTC, M-Blomqvist approved these changes

2021-05-07 10:34 UTC, merged